/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModelQueryLanguageTextualStandaloneSetup extends ModelQueryLanguageTextualStandaloneSetupGenerated {

	public static void doSetup() {
		new ModelQueryLanguageTextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
