/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import geodes.sms.modelquerylanguage.ModelQueryLanguageTextualRuntimeModule;
import geodes.sms.modelquerylanguage.ModelQueryLanguageTextualStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ModelQueryLanguageTextualIdeSetup extends ModelQueryLanguageTextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModelQueryLanguageTextualRuntimeModule(), new ModelQueryLanguageTextualIdeModule()));
	}
	
}
