/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.ide;


/**
 * Use this class to register ide components.
 */
public class ModelQueryLanguageTextualIdeModule extends AbstractModelQueryLanguageTextualIdeModule {
}
