/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.ui;

import com.google.inject.Injector;
import modelQueryLanguageTextual.ui.internal.ModelQueryLanguageTextualActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelQueryLanguageTextualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ModelQueryLanguageTextualActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ModelQueryLanguageTextualActivator activator = ModelQueryLanguageTextualActivator.getInstance();
		return activator != null ? activator.getInjector(ModelQueryLanguageTextualActivator.GEODES_SMS_MODELQUERYLANGUAGE_MODELQUERYLANGUAGETEXTUAL) : null;
	}

}
