/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModelQueryLanguageTextualScopeProvider extends DelegatingScopeProvider {
}
