/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.ui.tests;

import com.google.inject.Injector;
import modelQueryLanguageTextual.ui.internal.ModelQueryLanguageTextualActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ModelQueryLanguageTextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ModelQueryLanguageTextualActivator.getInstance().getInjector("geodes.sms.modelquerylanguage.ModelQueryLanguageTextual");
	}

}
