/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.parser.antlr;

import com.google.inject.Inject;
import geodes.sms.modelquerylanguage.parser.antlr.internal.InternalModelQueryLanguageTextualParser;
import geodes.sms.modelquerylanguage.services.ModelQueryLanguageTextualGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ModelQueryLanguageTextualParser extends AbstractAntlrParser {

	@Inject
	private ModelQueryLanguageTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModelQueryLanguageTextualParser createParser(XtextTokenStream stream) {
		return new InternalModelQueryLanguageTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "QueryFile";
	}

	public ModelQueryLanguageTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModelQueryLanguageTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
