/*
 * generated by Xtext 2.28.0
 */
package geodes.sms.modelquerylanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModelQueryLanguageTextualUiModule extends AbstractModelQueryLanguageTextualUiModule {

	public ModelQueryLanguageTextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
